package TestCases.PO;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class Student {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public Student(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void set_ID_inputFirstName(String key1) {
        By elem = By.id("inputFirstName");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void set_ID_inputLastName(String key2) {
        By elem = By.id("inputLastName");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key2);
    }

    public void set_ID_navbarDropdown() {
        By elem = By.id("navbarDropdown");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void fillForm(String key1, String key2, boolean key3, boolean key4) {
        if (key1 != null)
            set_ID_inputFirstName(key1);
        if (key2 != null)
            set_ID_inputLastName(key2);
        if (key3 != false)
            set_ID_navbarDropdown();
        if (key4 != false)
            fillForm11();
    }

    public String set_ID_navbarDropdown_1() {
        By elem = By.id("navbarDropdown");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void fillForm11() {
        By elem = By.id("navbarDropdown1");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public String set_ID_navbarDropdown1() {
        By elem = By.id("navbarDropdown1");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }
}
