// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestFormTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void Login() {
    driver.get("https://localhost:5001/");
    driver.manage().window().setSize(new Dimension(1075, 965));
    System.out.println("{ASSESSOR}:DashBoard:clickLoginButton");
    driver.findElement(By.linkText("Login")).click();
    System.out.println("{ASSESSOR}backToMain");
    System.out.println("{ASSESSOR}:Login:checkCorrectPage");
    assertThat(driver.findElement(By.cssSelector(".card-title")).getText(), is("Login"));
    System.out.println("{ASSESSOR}backToMain");
    System.out.println("{ASSESSOR}:Login:setCredential");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("eugenio.brandi3@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("*Fanta10");
    driver.findElement(By.name("Login")).click();
    System.out.println("{ASSESSOR}backToMain");
    System.out.println("{ASSESSOR}:DashBoard:checkCorrectResult");
    assertThat(driver.findElement(By.cssSelector(".blazored-toast-header")).getText(), is("SUCCESS"));
    System.out.println("{ASSESSOR}backToMain");
  }
}
