// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class adminLoginsuccessfulTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
 
  @Test
  public void testBackToFather() {  
	System.out.println("{ASSESSOR}:Login:TEST1");
	
	System.out.println("{ASSESSOR}:Login:ineer1");
    driver.findElement(By.name("_username")).sendKeys("admin@example.com");
	System.out.println("{ASSESSOR}backToFather");
	
	System.out.println("{ASSESSOR}:Login:inner2");
    driver.findElement(By.name("1")).sendKeys("com");
	System.out.println("{ASSESSOR}backToFather");
	
	System.out.println("{ASSESSOR}:Login:inner3");
    driver.findElement(By.name("2")).sendKeys("com");
	System.out.println("{ASSESSOR}backToFather");
	
	System.out.println("{ASSESSOR}backToMain");
	
  }
  
   @Test
  public void testNoBackToFather() {  
	System.out.println("{ASSESSOR}:Login:TEST2");
	
	System.out.println("{ASSESSOR}:Login:ineer1");
    driver.findElement(By.name("_username")).sendKeys("admin@example.com");
	
	System.out.println("{ASSESSOR}:Login:inner2");
    driver.findElement(By.name("1")).sendKeys("com");
		
	System.out.println("{ASSESSOR}backToMain");
	
  }
  
   
   @Test
  public void testNoBackToFather_assert_end() {  
   System.out.println("{ASSESSOR}:Login:TEST1");
	System.out.println("{ASSESSOR}:Login:ineer1");
    driver.findElement(By.name("_username")).click();
    driver.findElement(By.name("_username")).sendKeys("admin@example.com");
			
	System.out.println("{ASSESSOR}:Login:checkCorrectPage");
    assertThat(driver.findElement(By.cssSelector(".logo-lg")).getText(), is("Kimai - Time Tracking"));
    System.out.println("{ASSESSOR}backToMain");
  }
  
   @Test
  public void testNoBackToFather_assert_in() {  
   System.out.println("{ASSESSOR}:Login:TEST1");
	System.out.println("{ASSESSOR}:Login:ineer1");
    driver.findElement(By.name("_username")).click();
    driver.findElement(By.name("_username")).sendKeys("admin@example.com");
	System.out.println("{ASSESSOR}backToMain");
	System.out.println("{ASSESSOR}:Login:checkCorrectPage");
    assertThat(driver.findElement(By.cssSelector(".logo-lg")).getText(), is("Kimai - Time Tracking"));
	
	System.out.println("{ASSESSOR}:Login:inner2");
    driver.findElement(By.name("1")).click();
    driver.findElement(By.name("1")).sendKeys("com");
	
		
	
    System.out.println("{ASSESSOR}backToMain");
  }
  
   @Test
  public void testNoBackToFather_assert_start() {  
	System.out.println("{ASSESSOR}:Login:TEST1");
   
	System.out.println("{ASSESSOR}:Login:checkCorrectPage");
    assertThat(driver.findElement(By.cssSelector(".logo-lg")).getText(), is("Kimai - Time Tracking"));
   
	System.out.println("{ASSESSOR}:Login:ineer1");
    driver.findElement(By.name("_username")).click();
    driver.findElement(By.name("_username")).sendKeys("admin@example.com");
	
		

	
	
    System.out.println("{ASSESSOR}backToMain");
  }
}
